# Generated by Django 4.2.5 on 2023-09-15 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("online_store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="description",
            field=models.CharField(blank=True, default="", max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="image",
            field=models.ImageField(
                blank=True,
                default="",
                null=True,
                upload_to="online_store/static/images/",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="name",
            field=models.CharField(max_length=60),
        ),
    ]
